<div id="form_div_login">
<form action="{$element->getAction()}"
      method="{$element->getMethod()}"
      enctype="{$element->getAttrib('enctype')}"
      id="{$element->getId()}"
      name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
      {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
      class="form-horizontal">

    {$element->username}
    {$element->password}


    <div class="form-actions">
        <input class="btn btn-success" type="submit" value="Login" />
    </div>


</form>

</div> <!-- #form_div_login -->
