<div id="form_div_admin_password">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">

        <label for="passowrd" class="control-label">
    	    	{$element->new_password->getLabel()}
    	</label>
	    <div id="div-controls-{$element->new_password->getId()}" class="controls">
		    <div class="input-append">
		        {$element->new_password}
		        {if $element->new_password->getAttrib('disabled') != 'disabled'}
    		        <span id="password_rand" onclick="randPasword( 12, 'new_password' );" title="Random Password" class="btn add-on" style="margin-left: -5px;">
                        <i class="icon-refresh"></i>
                    </span>
                {/if}
		    </div>

        	{if $element->new_password->getMessages()}
				<script type="text/javascript">
					$( '#{$element->new_password->getId()}' ).addClass( 'error' );
					$( '#div-form-{$element->new_password->getId()}' ).addClass( 'error' );
				</script>
				{/if}
				<p id="help-{$element->new_password->getId()}" class="help-block">
				{if $element->new_password->getMessages()}
					{foreach from=$element->new_password->getMessages() item=messages}
    					{foreach from=$messages item=msg}
        					{$msg}<br />
    					{/foreach}
					{/foreach}
					{/if}
				</p>

	    </div>
        {if isset($element->email)}
            {include file='form/element-checkbox.phtml' ielement=$element->email}
        {/if}

        {if !isset( $modal) || !$modal}
        <fieldset class ="form-actions">
            <input class ="btn btn-primary" type="submit" value="{$element->change->getLabel()}" />
            <a class="btn" href="{genUrl controller=$controller}">Cancel</a>
        </fieldset>
        {/if}

</div> <!-- #form_div_admin_password -->
