<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Quota
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Quota extends EntityRepository
{
    /**
     * Get quota bytes for a username
     *
     * @param string $username
     * @return integer|null
     */
    public function getBytesForUsername($username)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('q.bytes')
            ->from('\\Entities\\Quota', 'q')
            ->where('q.username = ?1')
            ->setParameter(1, $username);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result ? $result['bytes'] : null;
    }
}
