<div id="form_div_change_mailbox_pwd">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">

        {$element->username}
        {$element->current_password}

        <fieldset class="control-group" id="div-form-new_password">
            <label for="new_password" class="control-label">{$element->new_password->getLabel()}</label>
            <div id="div-controls-new_password" class="controls">
                <div class="input-append">
                    {$element->new_password}
                    {$element->new_password_generator}
                </div>
            </div>
        </fieldset>

        {$element->confirm_new_password}

        <fieldset class="form-actions">
            <a class="btn" href="{genUrl controller='auth' action='login'}" >Cancel</a>
            &nbsp;
            <input class="btn btn-primary" type="submit" id="{$element->change->getId()}" value="{$element->change->getLabel()}" />
        </fieldset>
    </form>

</div>